config/routes.rb
WSWeb::Application.routes.draw do
  get "online_services/index"
  
  #match 'login'   => 'users/sessions#new'
  #match 'login'   => 'functions/login'

  match 'logout'  => 'users/sessions#destroy'
  match 'signup'  => 'users/registrations#new'
  
  namespace :users do
    resources :sessions,          :only => [:new, :create, :destroy]
    resources :forgot_passwords,  :only => [:new, :create]
    resources :registrations,     :only => [:new, :create]
    resources :profiles,          :only => [:new, :create]
  end


  root :to => 'functions#new'
  
  resources  :services,           :only => ['index']
  resources  :online_services,    :only => ['index']
  resources  :inquiries,          :only => ['new', 'create']

  #match "/sales/loadclients" => "sales#loadclients"
  #match "/sales/callclient1" => "sales#callclient1"
  #match "/functions/messages" => "functions#messages"
  
  resources :crews do
    collection do
      get 'tracker'
      get 'activity'
    end
    member do
      get 'activity'
      get 'job_details'
      post 'save_job'
    end
  end


  resources :employees do
    collection do
      get 'verpay'
      get 'showindpay'
      get 'showrangepay'
      post 'indpay'
      get 'rangepay'
      get 'deletepay'
      post 'createpay'
      get 'back_verpay'
      get 'back_rangepay'
      get 'recruiting_menu'
      get 'recruiters'
      post 'recruits'
      get 'recruits'
      get 'new_recruiters'
      get 'new_recruits'
      post 'save_recruiter'
      post 'save_recruit'
      post 'save_edit_recruit'
      post 'save_call_recruit'
      get 'make_schedule'
      post 'schedule'
      post 'save_schedule'
      get 'show_schedule'
      get 'show_training'
      post 'save_training'
      get 'show_recruits'
    end
    
    member do
      get 'recordpay'
      post 'savepay'
      get 'deletepay'
      get 'delete_recruit'
      get 'delete_recruiter'
      get 'edit_recruit'
      get 'call_recruit'
      get 'deleteschedule'
      get 'delete_training'
    end
  end

 
  resources :functions do
    collection do
      get 'sales_stats'
      post 'savedatacheck'
      post 'datacheck' 
      get 'showdatacheck' 
      get 'send_estimate_mail'
      get 'loginuser'
      post 'logoutuser'
      get 'login'
      post 'login'
      post 'findclients'   # /clients/count   helper_method: count_clients_path
      get 'smartsearch'
      get 'messagelog'
      get 'logmessage'
      post 'screenmessage'
      get 'loadsatisfaction'
      post 'satisfaction'
      get 'satisfaction1'
      get 'nextsat'
      get 'login1'
      get 'co_stats'
      get 'co_stats_septoct'
      get 'co_stats_novdec'
      get 'ind_stats'
      get 'ind_stats_7'
      get 'stats1'
      get 'stats_schedule'
      get 'stats_production'
      get 'new'
      get 'send_estimate_mail'
      get 'kill_stats'
    end
    member do
      get 'new'
      get 'clientprofile'
      post 'editclient'
      get 'makednf'
      post 'makednffromcfdetails'
      get 'modifydnf'
      post 'savemodifydnf'
      post 'savesatcall'
      get 'nextsatclient'
      get 'satisfaction_from_client_profile'
    end
  end
  resources :functions
  
  
  
  resources :sales do
    collection do 
      post 'loadclients'   # /clients/count   helper_method: count_clients_path
      get 'index'
      post 'calllog5'
      get 'newcalllog5'
      get 'schedule'
      get 'clientlist'
      get 'nextbatch'
      get 'findclients'
      get 'callprofile' 
      post 'searchclients'
      post 'assclients' 
      post 'callprofile1'
      get 'screenconvertcalls' 
      get 'screensales' 
      post 'actionclients'
      get 'saleshistory'
      get 'schedule'
      get 'calllog'
    end
    member do
#      get 'loadclient'  # /clients/:id/changeAddress   helper_method: changeAddress_client_path(:id)
      get 'callclient'
      post 'callclient1'
      get 'makesale'
      post 'makesale1'
      post 'makesalefromcfdetails'
      post 'savemodifysale'
      get 'modifysale'
      get 'nextclient'
      get 'previousclient'
      get 'deletecontact'
      get 'deletesale'
    end
  end
  
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  self.table_name= "hr"
  
  
  def self.just_id_from_name(key) 
    where("name= ? ", "#{key}").pluck('HRID') 
  end

  def self.just_name_from_id(key) 
    where("hrid= ? ", "#{key}").pluck('name') 
  end

  def self.name_from_id(key) 
    where("hrid= ? ", "#{key}") 
  end

  def self.find_by_hrid(key) 
    Employee.where("hrid= ? ", "#{key}") 
  end
  
  def self.find_by_name(key) 
    Employee.where("name= ? ", "#{key}") 
  end

  def self.active_sales_people 
    where("jobdesc like '%Sales Agent%' and status='active'").order('name')
  end

  def self.active_sales_people_only 
    where("jobdesc like '%Sales Agent%' and status='active'").order('name').pluck('name')
  end

  def self.active_people_only 
    where("status='active'").order('name').pluck('name')
  end


end
  

app/controllers/employees_controller.rb
class EmployeesController <  ApplicationController
  layout "application1"


  def verpay
    @open_sessions=Workschedule.find_open_sessions
    @open_sessions.each do |ws|
      names=Employee.just_name_from_id ws.HRID
      ws.HRID=names.first
    end
    @closed_sessions=Workschedule.find_closed_sessions
    @closed_sessions.each do |ws5|
      names=Employee.just_name_from_id ws5.HRID
      ws5.HRID=names.first
    end
  end
  
  def move_params params
      prep_showindpay
      @hrid=params[:hrid]    
      @person=params[:person]
      @selected_syear=params[:syear]
      @selected_smonth=params[:smonth]
      @selected_sday=params[:sday]
      @selected_fyear=params[:fyear]
      @selected_fmonth=params[:fmonth]
      @selected_fday=params[:fday]
      @selected_year5=params[:year5]
      @selected_month5=params[:month5]
      @selected_day5=params[:day5]
      sdate=Date.parse(@selected_syear.concat('-').concat(@selected_smonth).concat('-').concat(@selected_sday))
      fdate=Date.parse(@selected_fyear.concat('-').concat(@selected_fmonth).concat('-').concat(@selected_fday))
  
      @sessions=Workschedule.find_sessions sdate, fdate, @hrid
      @sessions.each do |ws5|
        names=Employee.just_name_from_id ws5.HRID
        ws5.HRID=names.first
      end

  end
    
  
  def recordpay
    @id=params[:id]
    @ws=Workschedule.find @id
    date=@ws.profiledate
    hrid=@ws.HRID
    if(!@ws.stime.nil?)
      @shour=@ws.stime.hour
      @smin=@ws.stime.min
    end
    if(!@ws.ftime.nil?)
      @fhour=@ws.ftime.hour
      @fmin=@ws.ftime.min
    end
    @rate=nil
    @rate='15.00'
    @rate=@rate.to_f
    if @ws.rate!='0.00'
      @rate=@ws.rate
      @rate=@rate.to_f
    end
    min_rate=@rate/60
    @rate=@rate.to_s
    shour1=HomeHelper.pad_num2 @shour
    smin1=HomeHelper.pad_num2 @smin
    fhour1=HomeHelper.pad_num2 @shour
    fmin1=HomeHelper.pad_num2 @fmin
    
    @selected_shour=HomeHelper.pad_num2 @shour
    @selected_smin=HomeHelper.pad_num2 @smin
    @selected_fhour=HomeHelper.pad_num2 @fhour
    @selected_fmin=HomeHelper.pad_num2 @fmin
#************************************************************************
    if smin1[1..1].to_i<5
      @selected_smin=smin1[0..0].concat('0')
    elsif smin1.to_i<=50 && smin1[1..1].to_i>5
      jj=smin1.to_i+10
      jj=HomeHelper.pad_num2 jj
      @selected_smin=jj[0..0].concat('0')
    elsif smin1.to_i>50 && smin1[1..1].to_i>5
      jj=shour1.to_i+1
      #jj=HomeHelper.pad_num2 jj
      @selected_shour=jj
      @selected_smin='0'
    end

    if fmin1[1..1].to_i<5
      @selected_fmin=fmin1[0..0].concat('0')
    elsif fmin1.to_i<=50 && fmin1[1..1].to_i>5
      jj=fmin1.to_i+10
      jj=HomeHelper.pad_num2 jj
      @selected_fmin=jj[0..0].concat('0')
    elsif fmin1.to_i>50 && fmin1[1..1].to_i>5
      jj=fhour1.to_i+1
      #jj=HomeHelper.pad_num2 jj
      @selected_fhour=jj
      @selected_fmin='0'
    end
#************************************************************************

    @selected_shour5=@selected_shour.to_i.to_s
    @selected_smin5=@selected_smin.to_i.to_s
    @selected_fhour5=@selected_fhour.to_i.to_s
    @selected_fmin5=@selected_fmin.to_i.to_s


        
    stotal_min=@selected_shour.to_i*60+@selected_smin.to_i
    ftotal_min=@selected_fhour.to_i*60+@selected_fmin.to_i
    
    total_min=ftotal_min-stotal_min
    @pay=total_min*min_rate
    
    #@hr_pay, 
    #@min_pay=total_min.divmod 60
    #if @hr_pay.nil?
    #  @hr_pay='0.00'
    #else
    #  @hr_pay=HomeHelper.pad_num2 @hr_pay
    #end
    #min_pay=HomeHelper.pad_num2 @min_pay
    #@hours=@hr_pay.to_s.concat(':').concat(@min_pay.to_s)
    
    @hours=total_min/60.to_f
    @hours=(@hours*100).round / 100.0
    @rate='15.00'
    if !@ws.rate.nil? && @ws.rate.to_f>'0.00'.to_f
      @rate=@ws.rate
      @rate=@rate.to_f
    end
    @pay=@hours*@rate.to_f

    
    
    names=Employee.just_name_from_id hrid
    @name=names.first
    #date=Date.parse('2013-08-27')

    @call_log=HomeHelper.generate_calllog hrid, date
    @record_pay_form=RecordPayForm.new
    @hour_options=HomeHelper::HOURS
    @min_options=HomeHelper::MIN
    @source=params[:source]
    if @source=='showindpay'
      move_params params
    end    
  end 
  
  def savepay
    rpf=params[:record_pay_form]
    id=rpf[:id]
    @ws=Workschedule.find id
    shr=params[:shr]  
    smin=params[:smin]  
    fhr=params[:fhr]  
    fmin=params[:fmin]
    hours=rpf[:hours]
    rate=rpf[:rate]
    rate=rate[1..rate.length]
    pay=rpf[:pay]
    pay=pay[1..pay.length]
    notes=rpf[:notes]
    @ws.stime=shr.concat(':').concat(smin).concat(':00')
    @ws.ftime=fhr.concat(':').concat(fmin).concat(':00')
    @ws.hours=hours
    @ws.rate=rate
    @ws.pay=pay
    @ws.notes=notes
    @ws.type5='Office'
    @ws.save!
    source=params[:source]
    if source=='showindpay'
      move_params params
      render 'showindpay'
      return
    else    
      redirect_to verpay_employees_url(:source=>source)
    end  
  end

 #:id => @hrid, :person=>@person, syear=>@selected_syear, :smonth=>@selected_smonth, :sday=>@selected_sday,
 # :fyear=>@selected_fyear, :fmonth=>@selected_fmonth, :fday=>@selected_fday, :source=>'showindpay' 

  def deletepay
    id=params[:id]
    
    ws=Workschedule.find id
    ws.destroy
    
    source=params[:source]
    if source=='showindpay'
      move_params params
      render 'showindpay'
      return  
    else
      redirect_to verpay_employees_url
      return
    end    
  end
  
  def prep_showindpay
    @spf=ShowPayForm.new
    @cpf=CreatePayForm.new
    @year_options=HomeHelper::YEARS  
    @month_options=HomeHelper::MONTHS
    @day_options=HomeHelper::DAYS
    d=Date.today.to_s
    @selected_syear=d[0..3]
    month=d[5..6]
    @selected_smonth=HomeHelper.get_month_from_num month
    @selected_sday=d[8..9]
    @selected_fyear=d[0..3]
    @selected_fmonth=HomeHelper.get_month_from_num month
    @selected_fday=d[8..9]
    @selected_year5=d[0..3]
    @selected_month5=HomeHelper.get_month_from_num month
    @selected_day5=d[8..9]
    names=Employee.active_people_only
    @caller_options=[]
    @caller_options<<'Everyone'
    @caller_options<<'Sales'
    @caller_options<<'Crew'
    names.each do |name|
        @caller_options<<name
    end
  end 
   
  def showindpay
    prep_showindpay
  end
  
  def showrangepay
    
  end

  
  def indpay
    spf=params[:show_pay_form]
    prep_showindpay
    @person=spf[:person]
    names=Employee.just_id_from_name @person
    @hrid=names.first
    @selected_syear=spf[:syear]
    @selected_smonth=spf[:smonth]
    @selected_sday=spf[:sday]
    @selected_fyear=spf[:fyear]
    @selected_fmonth=spf[:fmonth]
    @selected_fday=spf[:fday]
    sdate=Date.parse(@selected_syear+'-'+@selected_smonth+'-'+@selected_sday)
    fdate=Date.parse(@selected_fyear+'-'+@selected_fmonth+'-'+@selected_fday)

    @sessions=Workschedule.find_sessions sdate, fdate, @hrid
    @sessions.each do |ws5|
      names=Employee.just_name_from_id ws5.HRID
      ws5.HRID=names.first
    end
    
    render 'showindpay'  
  end
  
  def createpay
    cpf=params[:create_pay_form]
    prep_showindpay
    @hrid=cpf[:hrid]    
    @person=cpf[:person]
    @selected_syear=cpf[:syear]
    @selected_smonth=cpf[:smonth]
    @selected_sday=cpf[:sday]
    @selected_fyear=cpf[:fyear]
    @selected_fmonth=cpf[:fmonth]
    @selected_fday=cpf[:fday]
    @selected_year5=cpf[:year5]
    @selected_month5=cpf[:month5]
    @selected_day5=cpf[:day5]
    date=Date.parse(@selected_year5+'-'+@selected_month5+'-'+@selected_day5)
    ws=Workschedule.new
    ws.profiledate=date
    ws.HRID=@hrid
    ws.save

    sdate=Date.parse(@selected_syear+'-'+@selected_smonth+'-'+@selected_sday)
    fdate=Date.parse(@selected_fyear+'-'+@selected_fmonth+'-'+@selected_fday)

    @sessions=Workschedule.find_sessions sdate, fdate, @hrid
    @sessions.each do |ws5|
      names=Employee.just_name_from_id ws5.HRID
      ws5.HRID=names.first
    end
    render 'showindpay'  
  end

  def back_rangepay
    source=params[:source]
    if source=='showindpay'
      move_params params
      render 'showindpay'
      return
    end  
  end
  
  def back_verpay
    redirect_to verpay_employees_url
  end

  def recruiting_menu
    
  end
   
  def recruiters
    @recsupps= Recsupp.get_recruiters
  end  
  
  def show_recruits
    @show_recruits_form=ShowRecruitsForm.new
    @training_options=[]
    @training_options<<'none'
    @trainings= Training.find_trainings
    @trainings.each do |t|
      @training_options<<t.tdate.to_s
    end
    @status_options=['All']
    s1=HomeHelper::RECCALL
    s1.each do |s|
      @status_options<<s
    end
  end
  
  def recruits
    srf=params[:show_recruits_form]
    @recs=[]
    recs= Recruit.get_recruits
    recs.each do |rec|
      rb=RecruitBundle.new
#      date=Date.parse((rec.year).concat('-').concat(rec.month).concat('-').concat(rec.day))
      rb.date=rec.date  
      rb.source=rec.source
      rb.name=rec.name
      rb.address=rec.address
      rb.shop=rec.shop
      rb.phone=rec.phone
      rb.phone1=rec.phone1
      rb.email=rec.email
      rb.drive=rec.drive
      rb.ladder=rec.ladder
      rb.id=rec.id
      rb.status=rec.status
      if rec.training.nil?
        rb.training='none'
      else  
        rb.training=rec.training
      end
      
      calls=Reccontact.calls_to_recruit(rec.id)
      if calls.size!=0
        call=calls.last
        rb.category=call.category
        rb.catdate=call.actiondate
      end
      if srf[:status]=='All'
        @recs<<rb
      elsif srf[:status]==rb.category && srf[:training]==rb.training
        @recs<<rb
      end
      
    end
  end  


  def new_recruiters
    @new_recruiters_form=NewRecruitersForm.new
    @recsupps= Recsupp.get_recruiters
  end  
  
  def new_recruits
    @new_recruit_form=NewRecruitForm.new
    @recs= Recruit.get_recruits
    @year_options=HomeHelper::YEARS  
    @month_options=HomeHelper::MONTHS
    @day_options=HomeHelper::DAYS

app/views/employees/recruiting_menu.html.erb
<br/>

<%= link_to 'New Recruiters', new_recruiters_employees_path%><br/>
<%= link_to 'New Recruits', new_recruits_employees_path%><br/><br/>

<%= link_to 'Training Management', show_training_employees_path%><br/><br/>


<%= link_to 'Recruiters', recruiters_employees_path%><br/>
<%= link_to 'Recruits', show_recruits_employees_path%>

app/views/employees/recruits.html.erb
<b><%= link_to 'Main Menu', login1_functions_path%></b><br/>
<b><%= link_to 'Recruiting Menu', recruiting_menu_employees_path%></b><br/>
<b><%= link_to 'Recruits', show_recruits_employees_path%></b><br/><br/>


<fieldset class="mystyle">
	<legend>Recruits</legend>
	<%if !@recs.nil? && !@recs.empty?%>
	 	<table class="mystyle" border="1">
			<tr class="cell" border="1">
				<td>Name</td>
				<td>Cell Phone</td>
				<td>Home Phone</td>
				<td>Source</td>
				<td>Drive</td>
				<td>Status</td>
				<td>Category</td>
				<td>Action Date</td>
				<td>Training</td>
			</tr>
	    	<% @recs.each do |ws| %>
				<tr class="cell" border="1">
					<td><%=ws.name%></td>
					<td><%=ws.phone%></td>
					<td><%=ws.phone1%></td>
					<td><%=ws.source%></td>
					<td><%=ws.drive%></td>
					<td><%=ws.status%></td>
					<td><%=ws.category%></td>
					<td><%=ws.catdate%></td>
					<td><%=ws.training%></td>
					<td><%= link_to 'Edit', edit_recruit_employee_path(:id => ws.id),{:style=>"color: yellow"}%></td>
					<td><%= link_to 'Delete', delete_recruit_employee_path(:id => ws.id),{:style=>"color: yellow"}%></td>
					<td><%= link_to 'Recruit Call', call_recruit_employee_path(:id => ws.id),{:style=>"color: yellow"}%></td>
				</tr>
			<%end%>
		</table>
	<%end%>
</fieldset>

app/views/employees/showindpay.html.erb
<b><%= link_to 'Main Menu', login1_functions_path%></b><br/></br/>

<%= form_for @spf, :url => indpay_employees_url do |cc| %>
	<fieldset class="mystyle">
		<legend>Show Pays</legend>
		<table border="1" class="mystyle">
			<tr border="1" class="cell">
				<td><%=cc.label 'Start Date' %></td>
				<td>
					<%=cc.select :syear, options_for_select(@year_options, @selected_syear)%>
					<%=cc.select :smonth, options_for_select(@month_options, @selected_smonth)%>
					<%=cc.select :sday, options_for_select(@day_options, @selected_sday)%>
				</td>
			</tr>

			<tr border="1" class="cell">
				<td><%=cc.label 'Finish Date' %></td>
				<td>
					<%=cc.select :fyear, options_for_select(@year_options, @selected_fyear)%>
					<%=cc.select :fmonth, options_for_select(@month_options, @selected_fmonth)%>
					<%=cc.select :fday, options_for_select(@day_options, @selected_fday)%>
				</td>
			</tr>
			<tr border="1" class="cell">
				<td><%=cc.label 'Group/Individual' %></td>
				<td>
					<%=cc.select :person, options_for_select(@caller_options, @person)%>
				</td>
			</tr>
			<tr style="padding-top:10px" border="1" class="cell">
				<td colspan=3, align=center><%= cc.submit "Load Pays" %></td>
			</tr>
		</table>
	</fieldset>
<%end%>


<%= form_for @cpf, :url=>createpay_employees_url do |cc| %>
    <%=cc.hidden_field :hrid, value: @hrid%>
    <%=cc.hidden_field :person, value: @person%>
	<%=cc.hidden_field :syear, value: @selected_syear%>
	<%=cc.hidden_field :smonth, value: @selected_smonth%>
	<%=cc.hidden_field :sday, value: @selected_sday%>
	<%=cc.hidden_field :fyear, value: @selected_fyear%>
	<%=cc.hidden_field :fmonth, value: @selected_fmonth%>
	<%=cc.hidden_field :fday, value: @selected_fday%>
	<fieldset class="mystyle">
		<legend>Create Pay for&nbsp;<%=@person%></legend>
		<table border="1" class="mystyle">
			<tr border="1" class="cell">
				<td><%=cc.label 'Date' %></td>
				<td>
					<%=cc.select :year5, options_for_select(@year_options, @selected_year5)%>
					<%=cc.select :month5, options_for_select(@month_options, @selected_month5)%>
					<%=cc.select :day5, options_for_select(@day_options, @selected_day5)%>
				</td>
				<td><%= cc.submit "Create Pay" %></td>
			</tr>
		</table>
	</fieldset>
<%end%>





<fieldset class="mystyle">
<legend>Open/Closed Sessions</legend>
<%if !@sessions.nil? && !@sessions.empty?%>
 	<table class="mystyle" border="1">
		<tr class="cell" border="1">
			<td>Name</td>
			<td>Date</td>
			<td>Start Time</td>
			<td>Finish Time</td>
			<td>Hours</td>
			<td>Rate</td>
			<td>Pay</td>
			<td>Notes</td>
		</tr>
    	<% @sessions.each do |ws|
    		if !ws.stime.nil?
	    		String shour=ws.stime.hour.to_s 
	    	    if shour.length==1
	    	    	shour='0'+shour	
	    	    end
	    		String smin=ws.stime.min.to_s 
	    	    if smin.length==1
	    	    	smin='0'+smin	
	    	    end
    	    end
    	%>
		<tr class="cell" border="1">
			<td><%=ws.HRID %></td>
			<td><%=ws.profiledate.to_formatted_s(:long_ordinal) %></td>
			<%if !ws.stime.nil?%>
				<td><%=shour.concat(':').concat(smin) %></td>
			<%else%>
				<td>nil</td>	
			<%end%>
			<%if !ws.ftime.nil?
		   		String fhour=ws.ftime.hour.to_s 
		   	    if fhour.length==1
		   	    	fhour='0'+fhour	
		   	    end
		   		String fmin=ws.ftime.min.to_s 
		   	    if fmin.length==1
		   	    	fmin='0'+fmin	
		   	    end
			%>
				<td><%=fhour.concat(':').concat(fmin) %></td>
			<%else%>
				<td>nil</td>	
			<%end%>
				<td><%=ws.hours%></td>
				<td><%=number_to_currency ws.rate%></td>
				<td><%=number_to_currency ws.pay%></td>
				<td><b><%=ws.notes%></b></td>
				<td><b><%= link_to 'Record Pay', recordpay_employee_path(:id=>ws.id, :hrid => @hrid, :person=>@person, :syear=>@selected_syear, :smonth=>@selected_smonth, :sday=>@selected_sday, :fyear=>@selected_fyear, :fmonth=>@selected_fmonth, :fday=>@selected_fday, :source=>'showindpay'), :style=>"color: yellow"%></b></td>
				<td><b><%= link_to 'Delete Pay', deletepay_employee_path(:id=>ws.id, :hrid => @hrid, :person=>@person, :syear=>@selected_syear, :smonth=>@selected_smonth, :sday=>@selected_sday, :fyear=>@selected_fyear, :fmonth=>@selected_fmonth, :fday=>@selected_fday, :source=>'showindpay'), :style=>"color: yellow", :html=>{:confirm=>"Are you sure??"} %></b></td>
			</tr>
		<%end%>
	</table>
<%end%>

    

app/views/employees/verpay.html.erb
<b><%= link_to 'Main Menu', login1_functions_path%></b><br/><br/>

<fieldset class="mystyle">
<legend>Open/Closed Sessions</legend>
<%if !@loghours.nil? %>
	<%= link_to 'Log Me In', loginuser_functions_path(:hrid=>@hrid)%><br/><br/>
<%end%>


<%if !@open_sessions.nil? && !@open_sessions.empty?%>
 	<table class="mystyle" border="1">
			<tr class="cell" border="1">
				<td>Name</td>
				<td>Date</td>
				<td>Start Time</td>
				<td>Finish Time</td>
			</tr>
    	<% @open_sessions.each do |ws|
    		String shour=ws.stime.hour.to_s 
    	    if shour.length==1
    	    	shour='0'+shour	
    	    end
    		String smin=ws.stime.min.to_s 
    	    if smin.length==1
    	    	smin='0'+smin	
    	    end
    	%>

					<tr  class="cell" border="1">
						<td><%=ws.HRID %></td>
						<td><%=ws.profiledate.to_formatted_s(:long_ordinal) %></td>
						
						<%if !ws.stime.nil?%>
							<td><%=shour.concat(':').concat(smin) %></td>
						<%else%>
							<td>nil</td>	
						<%end%>
							<td>nil</td>	
					</tr>
		<%end%>
	</table>
<%end%>
<br/>	


<%if !@closed_sessions.nil? && !@closed_sessions.empty?%>
 	<table class="mystyle" border="1">
		<tr class="cell" border="1">
			<td>Name</td>
			<td>Date</td>
			<td>Start Time</td>
			<td>Finish Time</td>
			<td>Hours</td>
			<td>Rate</td>
			<td>Pay</td>
			<td>Notes</td>
		</tr>
    	<% @closed_sessions.each do |ws|
    		String shour=ws.stime.hour.to_s 
    	    if shour.length==1
    	    	shour='0'+shour	
    	    end
    		String smin=ws.stime.min.to_s 
    	    if smin.length==1
    	    	smin='0'+smin	
    	    end
    	%>
		<tr class="cell" border="1">
			<td><%=ws.HRID %></td>
			<td><%=ws.profiledate.to_formatted_s(:long_ordinal) %></td>
			<%if !ws.stime.nil?%>
				<td><%=shour.concat(':').concat(smin) %></td>
			<%else%>
				<td>nil</td>	
			<%end%>
			<%if !ws.ftime.nil?
		   		String fhour=ws.ftime.hour.to_s 
		   	    if fhour.length==1
		   	    	fhour='0'+fhour	
		   	    end
		   		String fmin=ws.ftime.min.to_s 
		   	    if fmin.length==1
		   	    	fmin='0'+fmin	
		   	    end
			%>
				<td><%=fhour.concat(':').concat(fmin) %></td>
			<%else%>
				<td>nil</td>	
			<%end%>
				<td><%=ws.hours%></td>
				<td><%=number_to_currency ws.rate%></td>
				<td><%=number_to_currency ws.pay%></td>
				<td><b><%=ws.notes%></b></td>
				<td><b><%= link_to 'Record Pay', recordpay_employee_path(:id => ws.id, :source=>'verpay'),:style=>"color: yellow"%></b></td>
				<td><b><%= link_to 'Delete Pay', deletepay_employee_path(:id => ws.id), :style=>"color: yellow", :confirm=>"Are you sure Sexy Twain?"  %></b></td>
			</tr>
		<%end%>
	</table>
<%end%>