config/routes.rb
WSWeb::Application.routes.draw do
  get "online_services/index"
  
  #match 'login'   => 'users/sessions#new'
  #match 'login'   => 'functions/login'

  match 'logout'  => 'users/sessions#destroy'
  match 'signup'  => 'users/registrations#new'
  
  namespace :users do
    resources :sessions,          :only => [:new, :create, :destroy]
    resources :forgot_passwords,  :only => [:new, :create]
    resources :registrations,     :only => [:new, :create]
    resources :profiles,          :only => [:new, :create]
  end


  root :to => 'functions#new'
  
  resources  :services,           :only => ['index']
  resources  :online_services,    :only => ['index']
  resources  :inquiries,          :only => ['new', 'create']

  #match "/sales/loadclients" => "sales#loadclients"
  #match "/sales/callclient1" => "sales#callclient1"
  #match "/functions/messages" => "functions#messages"
  
  resources :crews do
    collection do
      get 'tracker'
      get 'activity'
    end
    member do
      get 'activity'
      get 'job_details'
      post 'save_job'
    end
  end


  resources :employees do
    collection do
      get 'verpay'
      get 'showindpay'
      get 'showrangepay'
      post 'indpay'
      get 'rangepay'
      get 'deletepay'
      post 'createpay'
      get 'back_verpay'
      get 'back_rangepay'
      get 'recruiting_menu'
      get 'recruiters'
      post 'recruits'
      get 'recruits'
      get 'new_recruiters'
      get 'new_recruits'
      post 'save_recruiter'
      post 'save_recruit'
      post 'save_edit_recruit'
      post 'save_call_recruit'
      get 'make_schedule'
      post 'schedule'
      post 'save_schedule'
      get 'show_schedule'
      get 'show_training'
      post 'save_training'
      get 'show_recruits'
    end
    
    member do
      get 'recordpay'
      post 'savepay'
      get 'deletepay'
      get 'delete_recruit'
      get 'delete_recruiter'
      get 'edit_recruit'
      get 'call_recruit'
      get 'deleteschedule'
      get 'delete_training'
    end
  end

 
  resources :functions do
    collection do
      get 'sales_stats'
      post 'savedatacheck'
      post 'datacheck' 
      get 'showdatacheck' 
      get 'send_estimate_mail'
      get 'loginuser'
      post 'logoutuser'
      get 'login'
      post 'login'
      post 'findclients'   # /clients/count   helper_method: count_clients_path
      get 'smartsearch'
      get 'messagelog'
      get 'logmessage'
      post 'screenmessage'
      get 'loadsatisfaction'
      post 'satisfaction'
      get 'satisfaction1'
      get 'nextsat'
      get 'login1'
      get 'co_stats'
      get 'co_stats_septoct'
      get 'co_stats_novdec'
      get 'ind_stats'
      get 'ind_stats_7'
      get 'stats1'
      get 'stats_schedule'
      get 'stats_production'
      get 'new'
      get 'send_estimate_mail'
      get 'kill_stats'
    end
    member do
      get 'new'
      get 'clientprofile'
      post 'editclient'
      get 'makednf'
      post 'makednffromcfdetails'
      get 'modifydnf'
      post 'savemodifydnf'
      post 'savesatcall'
      get 'nextsatclient'
      get 'satisfaction_from_client_profile'
    end
  end
  resources :functions
  
  
  
  resources :sales do
    collection do 
      post 'loadclients'   # /clients/count   helper_method: count_clients_path
      get 'index'
      post 'calllog5'
      get 'newcalllog5'
      get 'schedule'
      get 'clientlist'
      get 'nextbatch'
      get 'findclients'
      get 'callprofile' 
      post 'searchclients'
      post 'assclients' 
      post 'callprofile1'
      get 'screenconvertcalls' 
      get 'screensales' 
      post 'actionclients'
      get 'saleshistory'
      get 'schedule'
      get 'calllog'
    end
    member do
#      get 'loadclient'  # /clients/:id/changeAddress   helper_method: changeAddress_client_path(:id)
      get 'callclient'
      post 'callclient1'
      get 'makesale'
      post 'makesale1'
      post 'makesalefromcfdetails'
      post 'savemodifysale'
      get 'modifysale'
      get 'nextclient'
      get 'previousclient'
      get 'deletecontact'
      get 'deletesale'
    end
  end
  
end

app/controllers/functions_controller.rb
class FunctionsController <  ApplicationController
  layout "application1"
  
    
  def new
    @mess=params[:mess]
    @login_form=Login1Form.new
  end
  
  def show 
  end
  
  def loghours
  end
  
  def time
  end

  def login
    login_form=params[:login1_form]
  #  puts '************LOGINFORM***************',login_form[0]
    if(login_form.nil?||login_form.empty?)
      puts 'Got In Here'
      redirect_to new_function_url(:mess=>'')
      return
    end  
    name=login_form[:name]
    pass=login_form[:password]
    @user=InternalUser.search(name,pass)  #@user is an array of InternalUser
    if !@user.empty? 
      user=@user[0]
      @username=user.username
      puts 'USER*************',@username
      hrid=user.HRID
      session[:username]=@username
      names=Employee.just_name_from_id (user.HRID)
      session[:fullname]=names[0]
      session[:hrid]=user.HRID
      session[:verify]='all good'
      render_login(hrid)
    else  
      redirect_to new_function_url(:mess=>'*****Incorrect Username/Password*****')
    end
  end
  
  def render_login(hrid)
      @loghours=nil
      @username=session[:username]
      @wslist=ws_list(hrid)
      if @wslist.nil? || @wslist.empty?
         @loghours='ok'
      else
        ws=@wslist.last
        if(!ws.ftime.nil?)
           @loghours='ok'
        end 
      end  
      @hrid=hrid
      @wslist.each do |ws|
        names=Employee.just_name_from_id(ws.HRID)
        ws.HRID=names.first
      end
      @work_schedule_form=WorkScheduleForm.new
      @open_sessions=Workschedule.current_open_sessions(hrid, Date.today)

      date10=Date.today + 10
      if @username=='roger' || @username=='shantz' || @username=='mattia' || @username=='derek'
        @sched=Schedule.get_schedule_all Date.today, date10
      else
        @sched=Schedule.get_schedule_ind @hrid, Date.today, date10
      end
      @sched=HomeHelper.sort_schedule @sched, @username
      render 'login5'
  end
  
  def ws_list(hrid)
    if @username=='Roger' || @username=='shantz'
      wslist=Workschedule.current_ind_all(Date.today)
    else   
      wslist=Workschedule.current_ind(hrid, Date.today)
    end
    return wslist
  end
  

  def loginuser
    hrid=params[:hrid]
    @wslist=ws_list(hrid)
    if !@wslist.nil?
      ws=@wslist.last
      if (ws.nil?)
        ws=Workschedule.new
        ws.HRID=hrid
        ws.profiledate=Date.today
        ws.stime=Time.now-14400
        ws.save
      elsif(!ws.nil?&&!ws.ftime.nil?)
        ws=Workschedule.new
        ws.HRID=hrid
        ws.profiledate=Date.today
        ws.stime=Time.now-14400
        ws.save
      end
    end
    @wslist=ws_list(hrid)
    render_login(hrid)
  end

  def logoutuser
    hrid=params[:hrid]
    log_out_form=params[:work_schedule_form]
    @wslist=ws_list(hrid)
    ws=@wslist.last
    ws.ftime=Time.now-14400
    ws.notes=log_out_form[:notes]
    ws.save
    @wslist=ws_list(hrid)
    render_login(hrid)
  end
  
  def login1
    @username=session[:username]
    @messsales=params[:messsales]
#    render 'login'
    hrid=session[:hrid]
    render_login(hrid)
  end
  
  def send_estimate_mail
    c=Client.find 'CF00024278'
    c.email='roger.whiteshark@hotmail.com'
    AppMailer.send_estimate_mail(c).deliver
    redirect_to login1_functions_url
  end
  
  
  def proceed verify
    verify=session[:verify]
    if verify!= 'all good' 
      redirect_to new_function_url(:mess=>'*****Incorrect Username/Password*****')
    end
  end
  
  def smartsearch
       
    ok=params[:verify]
    
    @verify=ok
    proceed @verify    
#    if !@verify.nil? 
      @smart_search_form=SmartSearchForm.new
#    else  
#      redirect_to new_function_url(:mess=>'*****Incorrect Username/Password*****')
#    end
  end

  def findclients
    @xx='Test'
    ssf=params[:smart_search_form]
    cfid=ssf[:CFID]
    if cfid!=''
      cfid=HomeHelper.pad_id_num('CF',cfid)
    end
    jobid=ssf[:jobid]
    if jobid!=''
      jobid=HomeHelper.pad_id_num('JB',jobid)
    end
    
    name=ssf[:name]
    address=ssf[:address]
    jobaddress=ssf[:jobaddress]
    phone=ssf[:phone]
    if cfid.eql? '' then
      cfid='Wayne Gretzky'
    end
    if jobid.eql? '' then
      jobid='Wayne Gretzky'
    end
    if name.eql? '' then
      name='Wayne Gretzky'
    end
    if address.eql? '' then
      address='Wayne Gretzky'
    end   
    if jobaddress.eql? '' then
      jobaddress='Wayne Gretzky'
    end   
    if phone.eql? '' then
      phone='Wayne Gretzky' 
    end
    @clients=Client.search1(name,address,phone, jobaddress, cfid, jobid)
 #   @props=Property.search(jobaddress)
 #   @props.each do |prop|
 #     cfid=prop.CFID
 #     c=Client.find(cfid)
 #     @clients<<c
 #   end   
    @clients=@clients.uniq
    @source=ssf[:source]
  end
  
  def clientprofile1
    @cfid=params[:id]
    @client=Client.find(@cfid)
    @nosale=params[:nosale]
    @cfmess=params[:cfmess]
    @source=params[:source]
    @function=params[:function]
    @jobid=params[:jobid]
    @jobid1=params[:jobid1]
    crs=Clientrate.find_rating @cfid
    cr=crs.first
    @client_header1= @client.CFID
    @client_header2=@client.full_name
    @client_header3=@client.address+' '+@client.phone
    @client_header4='Rating:'+cr.overallrate.to_s
    if @client.registerdate.nil? || @client.registerdate==''
      @client_header5='Date Registered: unknown'
    else 
      @client_header5='Date Registered:'+@client.registerdate.to_formatted_s(:long_ordinal)
    end
    @call_client_form=CallClientForm.new
    @sat_call_form=SatCallForm.new
    @tstatus_options=HomeHelper::CALL_OPTIONS
 
    date=HomeHelper.add_days_to_current_date(1)
    date10=HomeHelper.add_days_to_date date,10
    date10s=date10.to_s
    
    @selected_foll_year=date10s[0,4]
    @selected_foll_month=HomeHelper.get_month_from_num(date10s[5,2]) 
    @selected_foll_day=date10s[8,2]
 
    @year10=date10s[0,4]
    @month10=HomeHelper.get_month_from_num(date10s[5,2]) 
    @day10=date10s[8,2]
    
    
    @sat_options=HomeHelper::SAT_TYPES
    @years=HomeHelper::YEARS
    @months=HomeHelper::MONTHS
    @days=HomeHelper::DAYS
    @calls=@client.clientcontacts
    @call_info=[]      
    @date5=Date.parse("2013-04-01")

    if @function=='callclient'
      if !@calls.nil?
        @calls.each do |call|
          name='unknown'
          if !call.caller.nil?
            e=Employee.find(call.caller)
          end
          if !e.nil?
            call.caller=e.name
          else
            call.caller=name
          end  
        end
      end
    end
    
    
    if @function=='satcall'
      job=Job.find @jobid1
      @sat_info=[]      
      job_bundle=JobBundle.new
      job_bundle.jobdnf='job'
      job_bundle.jobid=job.JobID
      job_bundle.address=job.property.address
      job_bundle.jobdesc=job.JobDesc
      job_bundle.price=job.Price
      partner="".to_s
      empList=Employee.find_by_name(job.CrewName)
      emp=empList.last
      if(!emp.nil?)
        ocList=OC.find_partner  emp.HRID, job.Datebi
        oc=ocList.first
        if(!oc.nil?)
          emp2List=Employee.find_by_hrid oc.partner
          emp=emp2List.last
          if(!emp.nil?)
            partner="/" + emp.name.to_s
          end
        end
      end
      job_bundle.crewname=job.CrewName.to_s + partner.to_s
      job_bundle.minutes=job.Minutes
      job_bundle.datebi=job.Datebi
 
      if !job.Recstatus.nil? && !job.Recstatus.index('Receiv').nil? && job.Recstatus.index('Receiv')>-1
         job_bundle.daystopay=job.Recstatus
          @sat_info << job_bundle
      else       
        trandate=Transactions.date_paid job.JobID
        paid_date=trandate
        job_date=job.Datebi
        if(paid_date.nil? || job_date.nil?)
          job_bundle.daystopay='unknown'    
          @sat_info << job_bundle
        else  
          days=(paid_date-job_date).to_i
          job_bundle.daystopay=days    
          @sat_info << job_bundle
        end
      end
  
      upcomingdnfs=Jobdnf.search_incomplete_dnfs job.JobID
      upcomingdnfs.each do |dnf|
      job_bundle=JobBundle.new
      job_bundle.jobdnf='dnf'
      job_bundle.jobid=dnf.DNFID
      job_bundle.address=job.property.address
      job_bundle.jobdesc=dnf.DnfDesc
      if(dnf.Sdate==dnf.Fdate)
        job_bundle.type='Appt('+dnf.Stime+')'
      else  
        job_bundle.type='Fltr'
      end
      job_bundle.sdate=dnf.Sdate
      @sat_info << job_bundle
     end
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

    dnfs=Jobdnf.search_completed_dnfs(job.JobID)
    if !dnfs.nil?
      dnfs.each do |dnf|
        jdb=JobBundle.new
        jdb.jobdnf='dnf'
        jdb.jobid='DNF for:'+job.JobID
        jdb.address=job.property.address
        jdb.jobdesc=dnf.DnfDesc
        jdb.crewname=dnf.CrewName
        if !dnf.Datebi.nil?  
          partner="".to_s
          empList=Employee.find_by_name(dnf.CrewName)
          emp=empList.last
          if(!emp.nil?)
            ocList=OC.find_partner  emp.HRID, dnf.Datebi
            oc=ocList.first
              if(!oc.nil?)
                emp2List=Employee.find_by_hrid oc.partner
                emp=emp2List.last
                if(!emp.nil)
                  partner="/" + emp.name.to_s
                end
              end
          end
          job_bundle.crewname=job.CrewName.to_s + partner.to_s
        else
          job_bundle.crewname=''
        end
        jdb.minutes=dnf.Minutes
        jdb.datebi=dnf.Datebi
        jdb.daystopay='n/a'    
        @sat_info << jdb
      end
    end
    end
   
    @edit_client_form=EditClientForm.new
    @prices_all=HomeHelper::get_props_and_prices(@client)
    donejobs=@client.done_jobs
    donejobs2013=@client.done_jobs_2013
    upcomingjobs=@client.upcoming_jobs
    @done_jobs=[]
    @done_jobs_2013=[]
    @upcoming_jobs=[]
    upcomingjobs.each do |job|
      job_bundle=JobBundle.new
      job_bundle.jobdnf='job'
      job_bundle.jobid=job.JobID

app/views/functions/login.html.erb
<fieldset class="mystyle">
	<legend>Menu</legend>
		<b><%= link_to 'Smart Search', smartsearch_functions_path(:id => 'mikey')%></b><br/>
		<b><%= link_to 'Sales', sales_path%></b><br/>
		<b><%= link_to 'Sales History', saleshistory_sales_path%></b><br/>
		<b><%= link_to 'Schedule', schedule_sales_path%></b><br/>
		<b><%= link_to 'Messages', messagelog_functions_path%></b><br/>
		<b><%= link_to 'Create Message', logmessage_functions_path%></b><br/>
		<b><%= link_to 'Satisfaction Calls', loadsatisfaction_functions_path%></b><br/>
		<b><%= link_to 'Read Stats', stats1_functions_path%></b><br/><br/><br/>
		<b><a href="http://www.whiteshark.ca/internal">White Shark Internal</a></b><br/><br/>
	<%if @username=='Roger' || @username=='shantz' || @username=='Mac'%>
		<b><%= link_to 'Make Co Sales Stats', co_stats_functions_path%></b><br/>
		<b><%= link_to 'Make Ind Sales Stats7', ind_stats_7_functions_path%></b><br/>
		<b><%= link_to 'Make Ind Sales Stats', ind_stats_functions_path%></b><br/><br/>
	<%end%>	
	<%if @username=='Roger' || @username=='shantz'%>
		<b><%= link_to 'Send Estimate', send_estimate_mail_functions_path%></b><br/><br/><br/>
		<b><%= link_to 'Make Schedule Stats', stats_schedule_functions_path%></b><br/>
		<b><%= link_to 'Make Production Stats', stats_production_functions_path%></b><br/>
		<b><%= link_to 'Find Clients', findclients_sales_path%></b><br/>
		<b><%= link_to 'Call Profile', callprofile_sales_path%></b><br/>
		<b><%= link_to 'Add New Estimates to Call List (EHEH)', screenconvertcalls_sales_path%></b><br/>
		<b><%= link_to 'Add Sale Info to Call List (EHEH)', screensales_sales_path%></b><br/><br/>
		<%if !@messsales.nil?%>
			<b><%=@messsales%></b>
		<%end%> 
	<%end%>

</fieldset>

app/views/functions/login5.html.erb
<fieldset class="mystyle">
<legend>Current Time Logs</legend>
<%if !@loghours.nil? %>
	<%= link_to 'Log Me In', loginuser_functions_path(:hrid=>@hrid)%><br/><br/>
<%end%>	
<%if !@wslist.empty?%>
 	<table class="mystyle" border="1">
			<tr class="cell" border="1">
				<td>Name</td>
				<td>Date</td>
				<td>Start Time</td>
				<td>Finish Time</td>
				<td>Notes</td>
			</tr>
    	<% @wslist.each do |ws|
    		String shour=ws.stime.hour.to_s 
    	    if shour.length==1
    	    	shour='0'+shour	
    	    end
    		String smin=ws.stime.min.to_s 
    	    if smin.length==1
    	    	smin='0'+smin	
    	    end
    	%>

			<%if !ws.ftime.nil?%>
					<tr  class="cell" border="1">
						<td><%=ws.HRID %></td>
						<td><%=ws.profiledate.to_formatted_s(:long_ordinal) %></td>
						
						<%if !ws.stime.nil?%>
							<td><%=shour.concat(':').concat(smin) %></td>
						<%else%>
							<td>nil</td>	
						<%end%>
						<%if !ws.ftime.nil?
			    		String fhour=ws.ftime.hour.to_s 
			    	    if fhour.length==1
			    	    	fhour='0'+fhour	
			    	    end
			    		String fmin=ws.ftime.min.to_s 
			    	    if fmin.length==1
			    	    	fmin='0'+fmin	
			    	    end
						%>
							<td><%=fhour.concat(':').concat(fmin) %></td>
						<%else%>
							<td>nil</td>	
						<%end%>
						<td><b><%=ws.notes%></b></td>
						<%if @username=='shantz' || @username=='roger'|| @username=='mattia'%>
							<td><%= link_to 'Call Log', calllog_sales_path(:name => ws.HRID),:style=>"color: yellow"%></td>
						<%end%>
					</tr>
			<%else%>
				<%= form_for @work_schedule_form, :url =>logoutuser_functions_url(:hrid=>@hrid)  do |cc| %>
					<tr  class="cell" border="1">
						<td><%=ws.HRID %></td>
						<td><%=ws.profiledate.to_formatted_s(:long_ordinal) %></td>
						
						<%if !ws.stime.nil?%>
							<td><%=shour.concat(':').concat(smin) %></td>
						<%else%>
							<td>nil</td>	
						<%end%>
						<%if !ws.ftime.nil?
				    		String fhour=ws.ftime.hour.to_s 
				    	    if fhour.length==1
				    	    	fhour='0'+fhour	
				    	    end
				    		String fmin=ws.ftime.min.to_s 
				    	    if fmin.length==1
				    	    	fmin='0'+fmin	
				    	    end
						%>
							<td><%=fhour.concat(':').concat(fmin) %></td>
						<%else%>
							<td>nil</td>	
						<%end%>
						<td><b><%=cc.text_field :notes, :value=> ws.notes, :size=>"20x1" %></b></td>
						<%if @username=='shantz' || @username=='roger'|| @username=='mattia'%>
							<td><%= link_to 'Call Log', calllog_sales_path(:name => ws.HRID),:style=>"color: yellow"%></td>
						<%end%>
    					<td><%= cc.submit "Log Out" %></td>
					</tr>
				<%end%>		
			<%end%>
		<%end%>
	</table>
<%end%>
</fieldset>

<br/>
<br/>
<br/>
<%if @open_sessions>0 || (@username=='shantz' || @username=='roger' || @username=='derek'|| @username=='mattia')%>
<fieldset class="mystyle">
	<legend>Menu</legend>
<div id="nav">
	<ul id="menu">
		<li id="mainMenuClients">
			<b>Clients</b>
			<ul>
				<li><%= link_to 'Smart Search', smartsearch_functions_path%></li>
				<li><%= link_to 'Messages', messagelog_functions_path%></li>
				<li><%= link_to 'Create Message', logmessage_functions_path%></li>
			</ul>
		</li>
		<li id="mainMenuSales">
			<b>Sales</b>
			<ul>
				<li><%= link_to 'Sales', sales_path%></li>
				<li><%= link_to 'Daily Sales Stats', sales_stats_functions_path%></li>
				<li><%= link_to 'Read Co Sales Stats', stats1_functions_path%></li>
				<li><%= link_to 'Schedule', schedule_sales_path%></li>
				<li><%= link_to 'Sales History', saleshistory_sales_path%></li>
				<li><%= link_to 'Satisfaction Calls', loadsatisfaction_functions_path%></li>
			</ul>
		</li>
		<li id="mainMenuProduction">
			<b>Production</b>
			<ul>
				<li><%= link_to 'Crew Tracker', tracker_crews_path%></li>
			</ul>
		</li>
		<li id="mainMenuTasks">
			<b>Tasks</b>
			<ul>
				<li><%= link_to 'Make Production Stats', stats_production_functions_path%></li>
			</ul>
		</li>
		<li id="mainMenuHumanResources">
			<b>HR</b>
			<ul>
				<%if @username=='roger' || @username=='shantz' || @username=='derek'|| @username=='mattia'%>
					<li><%= link_to 'Verify Pay', verpay_employees_path%></li>
					<li><%= link_to 'Individual Pay', showindpay_employees_path%></li>
					<li><%= link_to 'Recruiting Menu', recruiting_menu_employees_path%></li>
					<li><%= link_to 'Make Schedule', make_schedule_employees_path%></li>
					<li><%= link_to 'Show Schedule', show_schedule_employees_path%></li>
				<%end%>
			</ul>
		</li>
		<li id="mainMenuStats">
			<b>Stats</b>
			<ul>
				<%if @username=='roger' || @username=='shantz'|| @username=='mattia'%>
					<li><%= link_to 'Read Co Sales Stats', stats1_functions_path%></li>
					<li><%= link_to 'Kill Stats', kill_stats_functions_path%></li>
					
					<li><%= link_to 'Make Co Summer Sales Stats', co_stats_functions_path%></li>
					<li><%= link_to 'Make Co Sept/Oct Sales Stats', co_stats_septoct_functions_path%></li>
					<li><%= link_to 'Make Co Nov/Dec Sales Stats', co_stats_novdec_functions_path%></li>
					<li><%= link_to 'Make Ind Sales Stats7', ind_stats_7_functions_path%></li>
					<li><%= link_to 'Make Ind Sales Stats', ind_stats_functions_path%></li>
					<li><%= link_to 'Make Schedule Stats', stats_schedule_functions_path%></li>
					<li><%= link_to 'Make Production Stats', stats_production_functions_path%></li>
				<%end%>
			</ul>
		</li>
		
		<li id="mainMenuManagement">
			<b>Management</b>
			<ul>
				<%if @username=='roger' || @username=='shantz' || @username=='derek'|| @username=='mattia'%>
					<li><%= link_to 'Call Log', newcalllog5_sales_path%></li>
				<%end%>	
				<%if @username=='roger' || @username=='shantz'|| @username=='mattia'%>
					<li><%= link_to 'Data Check', showdatacheck_functions_path%></li>
					<li><%= link_to 'Send Estimate', send_estimate_mail_functions_path%></li>
					<li><%= link_to 'Find Clients', findclients_sales_path%></li>
					<li><%= link_to 'Call Profile', callprofile_sales_path%></li>
					<li><%= link_to 'Add New Estimates to Call List (EHEH)', screenconvertcalls_sales_path%></li>
					<li><%= link_to 'Add Sale Info to Call List (EHEH)', screensales_sales_path%></li>
				<%end%>
			</ul>
		</li>
	</ul>

</div>

<br/>
<br/>
		<%if !@messsales.nil?%>
			<b><%=@messsales%></b>
		<%end%> 


		<b><a href="http://www.whiteshark.ca/internal">White Shark Internal</a></b><br/><br/>
	<%if @username=='roger' || @username=='shantz' || @username=='mattia'%>
	<%end%>	
	<%if @username=='roger' || @username=='shantz'|| @username=='mattia'%>
		<%if !@messsales.nil?%>
			<b><%=@messsales%></b>
		<%end%> 
	<%end%>

</fieldset>

<fieldset class="mystyle">
	<legend>Schedule</legend>
	<%if !@sched.nil? && !@sched.empty?%>
	 	<table class="mystyle" border="1">
			<tr class="cell" border="1">
				<td>Date</td>
				<td>Name</td>
				<td>Start Time</td>
				<td>Finish Time</td>
				<td>Tasks</td>
				<td>Notes</td>
			</tr>
	    	<% @sched.each do |ws| %>
	    	    
				<tr class="cell" border="1">
					<td><%=ws.date.strftime("%a%t%b%t%d")%></td>
					<td><%=ws.hrid%></td>
					<td><%=ws.stime%></td>
					<td><%=ws.ftime%></td>
					<td><%=ws.tasks%></td>
					<td><%=ws.notes%></td>
				</tr>
			<%end%>
		</table>
	<%end%>
</fieldset>
<%end%>

app/views/functions/new.html.erb
<%= form_for @login_form, :url => login_functions_url do |log| %>
	<fieldset class="mystyle">
	<%if !@mess.nil?%>
		<b><%=@mess%></b><br/><br/>
	<%end%>
		<legend>Log In Internal</legend>
	 	<b>Ruby Version 1.98&nbsp;&nbsp;&nbsp;October 24/13&nbsp;9 pm</b><br/>
 		<table class="mystyle" border="1">
			<tr  class="cell" border="1">
				<td><%=log.label :name %></td>
				<td>
					<%=log.text_field  :name, :size =>30 %>
				</td>
			</tr>
			<tr class="cell" border="1">
				<td><%= log.label :password %></td>
				<td>
					<%= log.password_field :password, :size => 30 %>
				</td>
			</tr>
				

			<tr style="padding-top:10px"  class="cell" border="1">
				<td>&nbsp;</td>
				<td><%= log.submit "Log In" %></td>
			</tr>
		</table>
	<br/><br/>
	</fieldset>
<% end%>