config/routes.rb
WSWeb::Application.routes.draw do
  get "online_services/index"
  
  #match 'login'   => 'users/sessions#new'
  #match 'login'   => 'functions/login'

  match 'logout'  => 'users/sessions#destroy'
  match 'signup'  => 'users/registrations#new'
  
  namespace :users do
    resources :sessions,          :only => [:new, :create, :destroy]
    resources :forgot_passwords,  :only => [:new, :create]
    resources :registrations,     :only => [:new, :create]
    resources :profiles,          :only => [:new, :create]
  end


  root :to => 'functions#new'
  
  resources  :services,           :only => ['index']
  resources  :online_services,    :only => ['index']
  resources  :inquiries,          :only => ['new', 'create']

  #match "/sales/loadclients" => "sales#loadclients"
  #match "/sales/callclient1" => "sales#callclient1"
  #match "/functions/messages" => "functions#messages"
  
  resources :crews do
    collection do
      get 'tracker'
      get 'activity'
    end
    member do
      get 'activity'
      get 'job_details'
      post 'save_job'
    end
  end


  resources :employees do
    collection do
      get 'verpay'
      get 'showindpay'
      get 'showrangepay'
      post 'indpay'
      get 'rangepay'
      get 'deletepay'
      post 'createpay'
      get 'back_verpay'
      get 'back_rangepay'
      get 'recruiting_menu'
      get 'recruiters'
      post 'recruits'
      get 'recruits'
      get 'new_recruiters'
      get 'new_recruits'
      post 'save_recruiter'
      post 'save_recruit'
      post 'save_edit_recruit'
      post 'save_call_recruit'
      get 'make_schedule'
      post 'schedule'
      post 'save_schedule'
      get 'show_schedule'
      get 'show_training'
      post 'save_training'
      get 'show_recruits'
    end
    
    member do
      get 'recordpay'
      post 'savepay'
      get 'deletepay'
      get 'delete_recruit'
      get 'delete_recruiter'
      get 'edit_recruit'
      get 'call_recruit'
      get 'deleteschedule'
      get 'delete_training'
    end
  end

 
  resources :functions do
    collection do
      get 'sales_stats'
      post 'savedatacheck'
      post 'datacheck' 
      get 'showdatacheck' 
      get 'send_estimate_mail'
      get 'loginuser'
      post 'logoutuser'
      get 'login'
      post 'login'
      post 'findclients'   # /clients/count   helper_method: count_clients_path
      get 'smartsearch'
      get 'messagelog'
      get 'logmessage'
      post 'screenmessage'
      get 'loadsatisfaction'
      post 'satisfaction'
      get 'satisfaction1'
      get 'nextsat'
      get 'login1'
      get 'co_stats'
      get 'co_stats_septoct'
      get 'co_stats_novdec'
      get 'ind_stats'
      get 'ind_stats_7'
      get 'stats1'
      get 'stats_schedule'
      get 'stats_production'
      get 'new'
      get 'send_estimate_mail'
      get 'kill_stats'
    end
    member do
      get 'new'
      get 'clientprofile'
      post 'editclient'
      get 'makednf'
      post 'makednffromcfdetails'
      get 'modifydnf'
      post 'savemodifydnf'
      post 'savesatcall'
      get 'nextsatclient'
      get 'satisfaction_from_client_profile'
    end
  end
  resources :functions
  
  
  
  resources :sales do
    collection do 
      post 'loadclients'   # /clients/count   helper_method: count_clients_path
      get 'index'
      post 'calllog5'
      get 'newcalllog5'
      get 'schedule'
      get 'clientlist'
      get 'nextbatch'
      get 'findclients'
      get 'callprofile' 
      post 'searchclients'
      post 'assclients' 
      post 'callprofile1'
      get 'screenconvertcalls' 
      get 'screensales' 
      post 'actionclients'
      get 'saleshistory'
      get 'schedule'
      get 'calllog'
    end
    member do
#      get 'loadclient'  # /clients/:id/changeAddress   helper_method: changeAddress_client_path(:id)
      get 'callclient'
      post 'callclient1'
      get 'makesale'
      post 'makesale1'
      post 'makesalefromcfdetails'
      post 'savemodifysale'
      get 'modifysale'
      get 'nextclient'
      get 'previousclient'
      get 'deletecontact'
      get 'deletesale'
    end
  end
  
end

app/views/shared/_eservices_menu.html.erb
	<ul id="eServicesMenu">
		<li><a href="#">Book a job</a></li>
		<li><a href="#">Manage/Pay recent and pending jobs</a></li>
		<li><%= link_to 'Update email address or password', new_users_profile_path %></li>
		<li><%= link_to 'Logout', logout_path %></li>
	</ul>

app/views/shared/_footer.html.erb
<footer>
	<div id="contact">
		<%= I18n.t(:white_shark_ltd) %> &nbsp;&nbsp;
		<%= image_tag 'contact_phone.gif' %>
		&nbsp;&nbsp;(416)363-7420&nbsp;&nbsp;
		<%= image_tag 'contact_email.gif' %>
		<a href="mailto:customerservice@whiteshark.ca">customerservice@whiteshark.ca</a>
	</div>
	<div>
		<center>
		<%= I18n.t(:call_us_or) %> <%= link_to I18n.t(:click_here), new_inquiry_path %> <%= I18n.t(:free_quote) %> 
		</center>
	</div>
</footer>

app/views/shared/_header.html.erb
<header id="pageHeader">
	<%= link_to "/" do %>
	<%= image_tag "sharklogo_t.gif", :id => "whiteshark_logo", :width => 135, :alt => I18n.t(:white_shark) %>
	<%= image_tag "extramile_t.gif", :id => "extramile_logo", :width => 187, :alt => I18n.t(:extra_mile) %>
	<div id="company">
		<h1><%= I18n.t(:white_shark_ltd) %></h1>
		<p>416-363-7420</p>
	</div>
	<% end %>
</header>

app/views/shared/_mainnav.html.erb
<div id="mainNav">
	<ul>
		<li id="nav_services">
			<%= link_to 'Our services', services_path, :title => "Our services" %>
			<em>Window, eaves cleaning, painting</em>
		</li>
		<li id="nav_quote">
			<%= link_to 'Obtain a quote', new_inquiry_path, :title => "Obtain a quote" %>
			<em>Free quote usually provided in a day</em>
		</li>
		<li id="nav_book">
			<%= link_to 'Book a job', online_services_path, :title => "Book a job" %>
			<em>Sign in, book or manage jobs</em>
		</li>
	</ul>
</div>