config/routes.rb
WSWeb::Application.routes.draw do
  get "online_services/index"
  
  #match 'login'   => 'users/sessions#new'
  #match 'login'   => 'functions/login'

  match 'logout'  => 'users/sessions#destroy'
  match 'signup'  => 'users/registrations#new'
  
  namespace :users do
    resources :sessions,          :only => [:new, :create, :destroy]
    resources :forgot_passwords,  :only => [:new, :create]
    resources :registrations,     :only => [:new, :create]
    resources :profiles,          :only => [:new, :create]
  end


  root :to => 'functions#new'
  
  resources  :services,           :only => ['index']
  resources  :online_services,    :only => ['index']
  resources  :inquiries,          :only => ['new', 'create']

  #match "/sales/loadclients" => "sales#loadclients"
  #match "/sales/callclient1" => "sales#callclient1"
  #match "/functions/messages" => "functions#messages"
  
  resources :crews do
    collection do
      get 'tracker'
      get 'activity'
    end
    member do
      get 'activity'
      get 'job_details'
      post 'save_job'
    end
  end


  resources :employees do
    collection do
      get 'verpay'
      get 'showindpay'
      get 'showrangepay'
      post 'indpay'
      get 'rangepay'
      get 'deletepay'
      post 'createpay'
      get 'back_verpay'
      get 'back_rangepay'
      get 'recruiting_menu'
      get 'recruiters'
      post 'recruits'
      get 'recruits'
      get 'new_recruiters'
      get 'new_recruits'
      post 'save_recruiter'
      post 'save_recruit'
      post 'save_edit_recruit'
      post 'save_call_recruit'
      get 'make_schedule'
      post 'schedule'
      post 'save_schedule'
      get 'show_schedule'
      get 'show_training'
      post 'save_training'
      get 'show_recruits'
    end
    
    member do
      get 'recordpay'
      post 'savepay'
      get 'deletepay'
      get 'delete_recruit'
      get 'delete_recruiter'
      get 'edit_recruit'
      get 'call_recruit'
      get 'deleteschedule'
      get 'delete_training'
    end
  end

 
  resources :functions do
    collection do
      get 'sales_stats'
      post 'savedatacheck'
      post 'datacheck' 
      get 'showdatacheck' 
      get 'send_estimate_mail'
      get 'loginuser'
      post 'logoutuser'
      get 'login'
      post 'login'
      post 'findclients'   # /clients/count   helper_method: count_clients_path
      get 'smartsearch'
      get 'messagelog'
      get 'logmessage'
      post 'screenmessage'
      get 'loadsatisfaction'
      post 'satisfaction'
      get 'satisfaction1'
      get 'nextsat'
      get 'login1'
      get 'co_stats'
      get 'co_stats_septoct'
      get 'co_stats_novdec'
      get 'ind_stats'
      get 'ind_stats_7'
      get 'stats1'
      get 'stats_schedule'
      get 'stats_production'
      get 'new'
      get 'send_estimate_mail'
      get 'kill_stats'
    end
    member do
      get 'new'
      get 'clientprofile'
      post 'editclient'
      get 'makednf'
      post 'makednffromcfdetails'
      get 'modifydnf'
      post 'savemodifydnf'
      post 'savesatcall'
      get 'nextsatclient'
      get 'satisfaction_from_client_profile'
    end
  end
  resources :functions
  
  
  
  resources :sales do
    collection do 
      post 'loadclients'   # /clients/count   helper_method: count_clients_path
      get 'index'
      post 'calllog5'
      get 'newcalllog5'
      get 'schedule'
      get 'clientlist'
      get 'nextbatch'
      get 'findclients'
      get 'callprofile' 
      post 'searchclients'
      post 'assclients' 
      post 'callprofile1'
      get 'screenconvertcalls' 
      get 'screensales' 
      post 'actionclients'
      get 'saleshistory'
      get 'schedule'
      get 'calllog'
    end
    member do
#      get 'loadclient'  # /clients/:id/changeAddress   helper_method: changeAddress_client_path(:id)
      get 'callclient'
      post 'callclient1'
      get 'makesale'
      post 'makesale1'
      post 'makesalefromcfdetails'
      post 'savemodifysale'
      get 'modifysale'
      get 'nextclient'
      get 'previousclient'
      get 'deletecontact'
      get 'deletesale'
    end
  end
  
end

app/controllers/sales_controller.rb
require 'date'
#    puts 'NEXT CLIENT FINISH ',Time.now.to_s
#    puts 'IN NEXT CLIENT II...',session[:num]

class SalesController < ApplicationController
  layout "application1"
  protect_from_forgery


  @indstats7={}     

  def newcalllog5
    @syear_options=HomeHelper::YEARS
    @smonth_options=HomeHelper::MONTHS
    @sday_options=HomeHelper::DAYS
    
    d=Date.today.to_s
    @selected_syear=d[0..3]
    month=d[5..6]
    @selected_smonth=HomeHelper.get_month_from_num month
    @selected_sday=d[8..9]
    @selected_fyear=d[0..3]
    @selected_fmonth=HomeHelper.get_month_from_num month
    @selected_fday=d[8..9]

    
    names=Employee.active_sales_people_only
    @caller_options=[]
    @caller_options<<'George Patsas'
    @caller_options<<'Ryan Carreira'
    names.each do |name|
        @caller_options<<name
    end
    @call_profile_form=CallProfileForm.new
  end
  
  def calllog5
    cpf=params[:call_profile_form]
    @name=cpf[:caller] 
    syear=cpf[:syear] 
    smonth=cpf[:smonth] 
    smonth=HomeHelper.get_num_from_month(smonth)
    sday=cpf[:sday]
    hrids=Employee.just_id_from_name @name 
    hrid=hrids[0]
    @date=Date.parse(syear+'-'+smonth+'-'+sday)
    @call_log=HomeHelper.generate_calllog hrid, @date
  end

  def calllog
    @name=params[:name]
    emp=Employee.find_by_name @name
    hrid=emp.first.HRID
    @date=Date.today
#    @cc=Clientcontact.calllog hrid, @today
#    @cc.each do |c|
#      client=Client.find c.CFID
#      c.CFID=c.CFID+'  '+client.full_name
#    end
    @call_log=HomeHelper.generate_calllog hrid, @date
    render 'calllog5'
  end
  
  def saleshistory
    hrid=session[:hrid]
    emp=Employee.name_from_id hrid
    name=emp.first.name
    soldjobs_summer2013=Job.jobs_sold_summer_by hrid
    soldjobs_fall2013=Job.jobs_sold_fall_by hrid
    @summer_jobs=[]
    @fall_jobs=[]
    soldjobs_summer2013.each do |job|
      job_bundle=JobBundle.new
      job_bundle.jobdnf='job'
      job_bundle.jobid=job.JobID
      job_bundle.address=job.property.address
      if job.JobDesc.size>15
        job.JobDesc=job.JobDesc[0..15]
      end
      job_bundle.jobdesc=job.JobDesc
      job_bundle.salesp=name
      job_bundle.datesold=job.Datesold
      job_bundle.price=job.Price
      if(job.Sdate==job.Fdate)
        job_bundle.type='Appt('+job.Stime+')'
      else  
        job_bundle.type='Fltr'
      end
      job_bundle.sdate=job.Sdate
      @summer_jobs << job_bundle
    end

    soldjobs_fall2013.each do |job|
      job_bundle=JobBundle.new
      job_bundle.jobdnf='job'
      job_bundle.jobid=job.JobID
      job_bundle.address=job.property.address
      if job.JobDesc.size>15
        job.JobDesc=job.JobDesc[0..15]
      end
      job_bundle.jobdesc=job.JobDesc
      job_bundle.salesp=name
      job_bundle.datesold=job.Datesold
      job_bundle.price=job.Price
      if(job.Sdate==job.Fdate)
        job_bundle.type='Appt('+job.Stime+')'
      else  
        job_bundle.type='Fltr'
      end
      job_bundle.sdate=job.Sdate
      @fall_jobs << job_bundle
    end

  end

  def screensales
    maxdate=Convertcall.max_datesold
    puts 'MAAXXXDDDAAATEEE',maxdate
    #maxdate1=Date.parse('2013-04-03')
    #maxdate2=Date.parse('2013-04-04')
    if Utils.get_jobid.nil?
      jobs=Job.jobs_sold_between(maxdate, Date.today, 'JB00000001')
    else
      jb=Utils.get_jobid
      jobs=Job.jobs_sold_between(maxdate, Date.today, jb)
    end
    jobs.each do |job|
      c=job.client
      ccs=Convertcall.find_by_cfid c.CFID
      cc=ccs.first
      if !cc.nil?
        cc.lastjob=job.Datesold
        puts 'Updated ',c.CFID,job.Datesold
        cc.save!
      end   
    end
    if(jobs.size!=0)
      lastjob=jobs.last
      Utils.set_jobid lastjob.JobID
    end
    mess="Screened Sales Up To Job ID:"+Utils.get_jobid
    redirect_to login1_functions_url(:messsales=> mess)    
  end




  def callprofile
    @cp_form=CallProfileForm.new
    cc=Convertcall.select(:hrid).uniq
    @caller_options=[]
    cc.each do |c|
      if !c.hrid.nil?
        emp=Employee.name_from_id c.hrid
        @caller_options<<emp.first.name
      end
    end
    @year_options=HomeHelper::YEARS
    @month_options=HomeHelper::MONTHS
    @day_options=HomeHelper::DAYS
  end

  def callprofile1
    cp=CallProfileForm.new(params[:call_profile_form])
    #sdate=Date.parse(cp_form.smonth.to_s +' '+ cp_form.sday.to_s+', '+ cp_form.syear.to_s)
    #fdate=Date.parse(cp_form.fmonth.to_s +' '+ cp_form.fday.to_s+', '+ cp_form.fyear.to_s)
    sdate=Date.parse(cp.smonth.to_s+' '+cp.sday.to_s+', '+cp.syear.to_s)
    fdate=Date.parse(cp.fmonth.to_s+' '+cp.fday.to_s+', '+cp.fyear.to_s)
    name=cp.caller
    emps=Employee.find_by_name name

  end 
   
  def findclients
    @find_client_form=FindClientForm.new
    @action_client_form=ActionClientForm.new
    @profile_options=HomeHelper::PROFILE_OPTIONS
    cc=Convertcall.select(:hrid).uniq
    @callers=[]
    cb=CallerBundle.new
    cb.name='Unassigned'
    cb.num=Convertcall.search_unassigned_all
        cb.fourseven=Convertcall.search_unassigned('4.6','4.7')     
        cb.fourfive=Convertcall.search_unassigned('4.4','4.5')    
        cb.fourthree=Convertcall.search_unassigned('4.2','4.3')    
        cb.fourone=Convertcall.search_unassigned('4.0','4.1') 
        cb.threenine=Convertcall.search_unassigned('3.7','3.9') 
        cb.threesix=Convertcall.search_unassigned('3.3','3.6') 
        cb.newests=Convertcall.search_unassigned_newestimates 
    @callers<<cb
    cc.each do |c|
      if !c.hrid.nil?
        cb=CallerBundle.new
        emp=Employee.name_from_id c.hrid
        cb.name=emp.first.name
        cb.num=Convertcall.search_assigned_by_holder_all c.hrid
        cb.fourseven=Convertcall.search_assigned_by_holder(c.hrid,'4.6','4.7')    
        cb.fourfive=Convertcall.search_assigned_by_holder(c.hrid,'4.4','4.5')    
        cb.fourthree=Convertcall.search_assigned_by_holder(c.hrid,'4.2','4.3')    
        cb.fourone=Convertcall.search_assigned_by_holder(c.hrid,'4.0','4.1')    
        cb.threenine=Convertcall.search_assigned_by_holder(c.hrid,'3.7','3.9')    
        cb.threesix=Convertcall.search_assigned_by_holder(c.hrid,'3.3','3.6')    
        cb.newests=Convertcall.search_assigned_by_holder(c.hrid,'2.5','2.5')    
        cb.lastsummer=Convertcall.search_assigned_by_holder_lastsummer c.hrid    
        @callers<<cb
      end
    end

    emps=Employee.active_sales_people
    @salesp_options=[]
    @salesp_options<<'Unassigned'
    emps.each do|emp|
      @salesp_options<<emp.name
    end        
    @ass_options=HomeHelper::ASS_OPTIONS

  end
  
  def actionclients
    acf=ActionClientForm.new(params[:action_client_form])
    profile=acf.profile
    limit=acf.limit
    from=acf.from
    from_hrid=nil
    to_hrid=nil
    
    if from=='Unassigned'
      from_hrid=nil
    else
      emp=Employee.find_by_name from
      from_hrid=emp.first.HRID
    end
    to=acf.to
    if to=='Unassigned'
      to_hrid=nil
    else
      emp=Employee.find_by_name to
      to_hrid=emp.first.HRID
    end
#        lowcf='CF00039366'
#puts action,profile,from_hrid
#    if action=='unassign'
      if profile=='4.0=>4.1 clients'
        cc=Convertcall.search_assigned_by_holder_cc(from_hrid, '4.0', '4.1')
      elsif profile=='4.2=>4.3 clients'
        cc=Convertcall.search_assigned_by_holder_cc(from_hrid, '4.2', '4.3')
      elsif profile=='4.4=>4.5 clients'
        cc=Convertcall.search_assigned_by_holder_cc(from_hrid, '4.4', '4.5')
      elsif profile=='4.6=>4.7 clients'
        cc=Convertcall.search_assigned_by_holder_cc(from_hrid, '4.6', '4.7')
      elsif profile=='3.7=>3.9 clients'
        cc=Convertcall.search_assigned_by_holder_cc(from_hrid, '3.7', '3.9')
      elsif profile=='3.3=>3.6 clients'
        cc=Convertcall.search_assigned_by_holder_cc(from_hrid, '3.3', '3.6')
      elsif profile=='New Estimates'
        cc=Convertcall.search_assigned_by_holder_newestimates_cc from_hrid  
      elsif profile=='Used Us Last Summer'
        cc=Convertcall.search_assigned_by_holder_lastsummer_cc from_hrid  
      end
    puts 'CC SIZE.......',cc.size
    i=0
    lim=limit.to_i
      cc.each do |c|
        if i==lim
          break 
        end
        c.hrid=to_hrid
        c.save!
        puts 'TRANSFERRED TO '.concat(c.cfid.to_s).concat(c.hrid.to_s)
        i+=1   
      end
    redirect_to findclients_sales_url    
  end
  
  def searchclients
    fcf=FindClientForm.new(params[:find_client_form])
    session[:assprofile]=fcf.profile
    if fcf.lowcf!=''
      fcf.lowcf=HomeHelper.pad_id_num('CF',fcf.lowcf)
    end
    
    session[:asslowcf]=fcf.lowcf
    session[:asslimit]=fcf.limit
    @cc=[]
  #    PROFILE_OPTIONS=['4.1+ clients', 'Used Us Last Summer']
    if fcf.profile=='4.0=>4.1 clients'
      @cc=Convertcall.available_ratings fcf.lowcf, fcf.limit, '4.0', '4.1'
    elsif fcf.profile=='4.2=>4.3 clients'
      @cc=Convertcall.available_ratings  fcf.lowcf, fcf.limit, '4.2', '4.3'
    elsif fcf.profile=='4.4=>4.5 clients'
      @cc=Convertcall.available_ratings  fcf.lowcf, fcf.limit, '4.4', '4.5'
    elsif fcf.profile=='4.6=>4.7 clients'
      @cc=Convertcall.available_ratings  fcf.lowcf, fcf.limit, '4.6', '4.7'
    elsif fcf.profile=='3.7=>3.9 clients'
      @cc=Convertcall.available_ratings  fcf.lowcf, fcf.limit, '3.7', '3.9'
    elsif fcf.profile=='3.3=>3.6 clients'
      @cc=Convertcall.available_ratings  fcf.lowcf, fcf.limit, '3.3', '3.6'
    elsif fcf.profile=='New Estimates'
      lowcf=fcf.lowcf
      if lowcf<'CF00039366'
        lowcf='CF00039366'
      end
      @cc=Convertcall.available_new_estimates  lowcf, fcf.limit
    elsif fcf.profile=='Used Us Last Summer'
      @cc=Convertcall.available_lastsummer fcf.lowcf, fcf.limit  
    end
    @assign_client_form=AssignClientForm.new
    emps=Employee.active_sales_people
    @salesp_options=[]
    emps.each do|emp|
      @salesp_options<<emp.name
    end        
  end
  
  def assclients
    acf=AssignClientForm.new(params[:assign_client_form])

app/views/sales/callclient.html.erb
<%=@x%>
<%  if !@calls.nil? then %>
	
	<table border="1" class="mystyle">
				<tr border="1" class="cell">
					<th>Status</th>
					<th>Date Att</td>
					<th>Caller</th>
					<th>Notes</th>
					<th>Follow Up</th>
				</tr>
   	<% @calls.each do |call|
       	dateatt=''
       	if call.dateatt.nil?
       		dateatt='unknown'
       	else	
       		dateatt=call.dateatt.to_formatted_s(:long_ordinal)
       	end
       	followup=''
       	if call.followup.nil?
       		followup='unknown'
       	else 
		       	followup=call.followup.to_formatted_s(:long_ordinal)
       	end
	%>
        
				<tr border="1" class="cell">
					<td><%=call.tstatus %></td>
					<td><%=dateatt%></td>
					<td><%=call.caller%></td>
					<td><%=call.notes%></td>
					<td><%=followup%></td>
				</tr>
        <% 	end %>
			</table>
        <% end%>
        <br/><br/>
        <%  if !@prices_all.nil? then
	        	@prices_all.each do |price|
        %>
	 			<table border="1" class="mystyle">
					<tr border="1" class="cell">
						<td>ID</td>
						<td>Address</td>
						<td>W1</td>
						<td>EH</td>
					</tr>
					<tr border="1" class="cell">
						<td><%=price.id %></td>
						<td><%=price.address %></td>
						<td><%=sprintf("$%0.02f", price.w1) %></td>
						<td><%=sprintf("$%0.02f", price.eh) %></td>
						<td><%=link_to 'Make Sale', makesale_sale_path(:jobinfoid => price.id, :source=>'tsales'),:style=>"color: yellow"%>
					</tr>
				</table>
        <% 	end
          end
        %>
        <br/><br/>


<%= form_for @call_client_form, :url => callclient1_sale_url(:id => @cfid) do |cc| %>
	<fieldset class="mystyle">
		<legend>Call Client</legend>
		    <%=cc.hidden_field :cfid, :value=>@cfid%>
 		<table border="1" class="mystyle">
			<tr class="cell">
				<td><%=cc.label :tstatus, "TStatus: " %></td>
				<td>
					<%=cc.select :tstatus, options_for_select(@tstatus_options, @selected_tstatus)%>
				</td>
			</tr>
			<tr border="1" class="cell">
				<td><%= cc.label :notes, "Notes: " %></td>
				<td>
					<%= cc.text_field :notes, :size => 30 %>
				</td>
			</tr>
			<tr border="1" class="cell">
				<td><%= cc.label :year, "Follow Up: " %></td>
				<td>
					<%=cc.select :year, options_for_select(@years,@selected_year)%>
					<%=cc.select :month, options_for_select(@months,@selected_month)%>
					<%=cc.select :day, options_for_select(@days,@selected_day)%>
				</td>
			</tr>
			<tr style="padding-top:10px" border="1" class="cell">
				<td>&nbsp;</td>
				<td><%= cc.submit "Call Client" %></td>
			</tr>
		</table>
	</fieldset>
<%end%>	

<b><%= link_to 'Call Next Client', nextclient_sale_path(:id => @cfid)%></b> <br/>

<b><%= link_to 'Client Profile', clientprofile_function_path(:id => @cfid,:source=>'callclient')%></b><br/>

<b><%= link_to 'Client List', clientlist_sales_path,%></b><br/>

app/views/sales/calllog.html.erb
<b><%= link_to 'Main Menu', login1_functions_path%></b><br/>
<b><%= link_to 'Back To Stats', stats1_functions_path%></b><br/><br/>

<% if !@cc.nil?%>
		<b>Call Log for&nbsp;<%=@name%>&nbsp;on&nbsp;<%=@today.to_formatted_s(:long_ordinal) %></b>
		<table border="1" class="mystyle">
				<tr class="cell">
					<th><b>Time of Call</b></th>
				</tr>	
			<%@cc.each do |c|%>
				<tr class='cell'>
					<td><b><%= c.CFID%></b></td>
					<td><b><%= c.callmade.to_s[11..18]%></b></td>
				</tr>	
			<%end%>
		</table>
<%end%>

app/views/sales/callprofile1.html.erb
ok

app/views/sales/findclients.html.erb
<b>Sorry Natalie!!</b>

<b><%= link_to 'Main Menu', login1_functions_path%></b><br/><br/>

<% if !@callers.nil? %>
	        <h2>Holder Profile</h2>
			<table border='1' class="mystyle">
				
			    	<tr border="1" class="cell"> 
						<th>Holder</th>
						<th>Number</th>
						<th>Rating 4.6-4.7</th>
						<th>Rating 4.4-4.5</th>
						<th>Rating 4.2-4.3</th>
						<th>Rating 4.0-4.1</th>
						<th>Rating 3.7-3.9</th>
						<th>Rating 3.3-3.6</th>
						<th>New Estimates</th>
					</tr>
				
				
				<% @callers.each do |c| %>
		    		<tr border="1" class="cell">
						<td><%= c.name %></td>
						<td><%= c.num %></td>
						<td><%= c.fourseven %></td>
						<td><%= c.fourfive %></td>
						<td><%= c.fourthree %></td>
						<td><%= c.fourone %></td>
						<td><%= c.threenine %></td>
						<td><%= c.threesix %></td>
						<td><%= c.newests %></td>
					</tr>
				<% end %>
			</table>
<% end %>
<br/><br/>
<%= form_for @action_client_form, :url => actionclients_sales_url do |action| %>
	<fieldset class="mystyle">
		<legend>Action On Clients</legend>
		<table border="1" class="mystyle">
			<tr border="1" class="cell">
				<td><%= action.label :profile %></td>
				<td>
					<%=action.select :profile, options_for_select(@profile_options, @selected_profile)%>
				</td>
			</tr>


			<tr border="1" class="cell">
				<td><%= action.label :from %></td>
				<td>
					<%=action.select :from, options_for_select(@salesp_options, @selected_salesp)%>
				</td>
			</tr>

			<tr border="1" class="cell">
				<td><%= action.label :to %></td>
				<td>
					<%=action.select :to, options_for_select(@salesp_options, @selected_salesp)%>
				</td>
			</tr>

			<tr border="1" class="cell">
				<td><%= action.label :limit %></td>
				<td>
					<%= action.text_field :limit, :size => 30 %>
				</td>
			</tr>



			<tr style="padding-top:10px" border="1" class="cell">
				<td>&nbsp;</td>
				<td><%= action.submit "Action Clients" %></td>
			</tr>
		</table>
	</fieldset>
<%end%>	

<br/><br/>

<%= form_for @find_client_form, :url => searchclients_sales_url do |sales| %>
	<fieldset class="mystyle">
		<legend>Find Clients</legend>
		<table border="1" class="mystyle">
			<tr border="1" class="cell">
				<td><%= sales.label :profile %></td>
				<td>
					<%=sales.select :profile, options_for_select(@profile_options, @selected_profile)%>
				</td>
			</tr>
			<tr border="1" class="cell">
				<td><%= sales.label :lowcf, "Low CF: " %></td>
				<td>
					<%= sales.text_field :lowcf, :value=>@lowcf, :size => 30 %>
				</td>
			</tr>
			<tr border="1" class="cell">
				<td><%= sales.label :limit %></td>
				<td>
					<%= sales.text_field :limit, :value=>@limit, :size => 30 %>
				</td>
			</tr>
			<tr style="padding-top:10px" border="1" class="cell">
				<td>&nbsp;</td>
				<td><%= sales.submit "Find Clients" %></td>
			</tr>
		</table>
	</fieldset>
<%end%>	

app/views/sales/index.html.erb
<b><%= link_to 'Main Menu', login1_functions_path%></b><br/>
<b><%= link_to 'Load Next Batch Of Clients', nextbatch_sales_path%></b><br/><br/><br/>



<% if !@cb.nil? %>
	        <h2>Profile</h2>
			<table border='1' class="mystyle">
				
			    	<tr border="1" class="cell"> 
						<th>Holder</th>
						<th>Number</th>
						<th>Rating 4.6-4.7</th>
						<th>Rating 4.4-4.5</th>
						<th>Rating 4.2-4.3</th>
						<th>Rating 4.0-4.1</th>
						<th>Rating 3.7-3.9</th>
						<th>Rating 3.3-3.6</th>
						<th>New Estimates</th>
					</tr>
				
				
		    		<tr border="1" class="cell">
						<td><%= @cb.name %></td>
						<td><%= @cb.num %></td>
						<td><%= @cb.fourseven %></td>
						<td><%= @cb.fourfive %></td>
						<td><%= @cb.fourthree %></td>
						<td><%= @cb.fourone %></td>
						<td><%= @cb.threenine %></td>
						<td><%= @cb.threesix %></td>
						<td><%= @cb.newests %></td>
					</tr>
		    		<tr border="1" class="cell">
						<td><%= "Zero Calls" %></td>
						<td><%= @cb.num %></td>
						<td><%= @cb.fourseven_zero %></td>
						<td><%= @cb.fourfive_zero %></td>
						<td><%= @cb.fourthree_zero %></td>
						<td><%= @cb.fourone_zero %></td>
						<td><%= @cb.threenine_zero %></td>
						<td><%= @cb.threesix_zero %></td>
						<td><%= @cb.newests_zero %></td>
					</tr>
		    		<tr border="1" class="cell">
						<td><%= "Highest CF Today" %></td>
						<td><%= @cb.num %></td>
						<td><%= @cb.fourseven_highcf %></td>
						<td><%= @cb.fourfive_highcf %></td>
						<td><%= @cb.fourthree_highcf %></td>
						<td><%= @cb.fourone_highcf %></td>
						<td><%= @cb.threenine_highcf %></td>
						<td><%= @cb.threesix_highcf %></td>
						<td><%= @cb.newests_highcf %></td>
					</tr>
			</table>
<% end %>
<br/><br/>





<%= form_for @sales_form, :url => loadclients_sales_url do |sales| %>
	<fieldset class="mystyle">
		<legend>Load Clients</legend>
		<table border="1" class="mystyle">
			<tr border="1" class="cell">
				<td><%= sales.label :profile, "Profile: " %></td>
				<td>
					<%=sales.select :profile, options_for_select(@profile_options, @selected_profile)%>
				</td>
			</tr>
			<tr border="1" class="cell">
				<td><%= sales.label :profile, "# Calls Before Today: " %></td>
				<td> 
					<%=sales.select :numcalls, options_for_select(@num_calls_options, @selected_num_calls)%>
				</td>
			</tr>
			<tr border="1" class="cell">
				<td><%= sales.label :lowcf, "Low CF: " %></td>
				<td>
					<%= sales.text_field :lowcf, :value=>@lowcf, :size => 30 %>
				</td>
			</tr>
			<tr border="1" class="cell">
				<td><%= sales.label :limit %></td>
				<td>
					<%= sales.text_field :limit, :value=>@limit, :size => 30 %>
				</td>
			</tr>
			<tr style="padding-top:10px" border="1" class="cell">
				<td>&nbsp;</td>
				<td><%= sales.submit "Load Clients" %></td>
			</tr>
		</table>
	</fieldset>
<%end%>	

app/views/sales/selljob.html.erb
@test